// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lkD2_I4Qlj6oulpPm6n8oKXeHJEoNcQ',
    appId: '1:466816962287:web:78d69bca0ddbadaa2b551a',
    messagingSenderId: '466816962287',
    projectId: 'todolistapp2025',
    authDomain: 'todolistapp2025.firebaseapp.com',
    storageBucket: 'todolistapp2025.firebasestorage.app',
    measurementId: 'G-H5W2D3HDMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGXzkmTBLbhvgzubnTCkBRNQ9j-edZ4Q',
    appId: '1:466816962287:android:d2d17001d83485c72b551a',
    messagingSenderId: '466816962287',
    projectId: 'todolistapp2025',
    storageBucket: 'todolistapp2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsiEToWpIffHbrUQLPvWQQn8GxTPwzm98',
    appId: '1:466816962287:ios:19ac93fdb8ae3a322b551a',
    messagingSenderId: '466816962287',
    projectId: 'todolistapp2025',
    storageBucket: 'todolistapp2025.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsiEToWpIffHbrUQLPvWQQn8GxTPwzm98',
    appId: '1:466816962287:ios:19ac93fdb8ae3a322b551a',
    messagingSenderId: '466816962287',
    projectId: 'todolistapp2025',
    storageBucket: 'todolistapp2025.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6lkD2_I4Qlj6oulpPm6n8oKXeHJEoNcQ',
    appId: '1:466816962287:web:c8d47dc4d2f2b09f2b551a',
    messagingSenderId: '466816962287',
    projectId: 'todolistapp2025',
    authDomain: 'todolistapp2025.firebaseapp.com',
    storageBucket: 'todolistapp2025.firebasestorage.app',
    measurementId: 'G-L0J60D2B3B',
  );
}
